
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import File.DataSewaBoss;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author lenovo
 */
public class formulirBOOKING extends javax.swing.JPanel {
    private DefaultTableModel model;
    private DaftarBooking Daftar1;
    private ArrayList<DataSewaBoss> dataList = new ArrayList<>();



    /**
     * Creates new form formulirBOOKING+
     */
    public formulirBOOKING(DaftarBooking daftarBooking) {
        initComponents();
        this.Daftar1 = daftarBooking;
        
        model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"Nama Penyewa", "Jenis Lapangan", "Tanggal Sewa", "Jenis Hari", "Waktu Sewa", "Harga", "Pelunasan"});
        jTable1.setModel(model);
    }
      public void loadDataFromFile() {
       try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream("dataPenyewaan.ser"))) {
        dataList = (ArrayList<DataSewaBoss>) ois.readObject();
        model.setRowCount(0);

        // Menambahkan data ke dalam tabel
        for (DataSewaBoss data : dataList) {
            model.addRow(new Object[]{
                data.getNama(), 
                data.getJenisLapangan(), 
                data.getTanggalSewa(), 
                data.getJenisHari(), 
                data.getWaktuSewa(), 
                data.getHarga(), 
                data.getPelunasan()
            });
        }
    } catch (FileNotFoundException e) {
        System.out.println("File tidak ditemukan: " + e.getMessage());
    } catch (IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error saat membaca file data!", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (ClassNotFoundException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Class tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
//        public void saveDataToFile() {
//        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("dataPenyewaan.ser"))) {
//            oos.writeObject(dataList);
//            JOptionPane.showMessageDialog(this, "Data berhasil disimpan!", "Info", JOptionPane.INFORMATION_MESSAGE);
//        } catch (IOException e) {
//            JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JnsLap = new javax.swing.JComboBox<>();
        TGLSewa = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NamaPenyewa = new javax.swing.JTextField();
        WktSewa = new javax.swing.JLabel();
        mulai = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        selesai = new javax.swing.JComboBox<>();
        JnsHari = new javax.swing.JLabel();
        Hari = new javax.swing.JComboBox<>();
        Total = new javax.swing.JLabel();
        Tott = new javax.swing.JTextField();
        metodePembayaran = new javax.swing.JLabel();
        transfer = new javax.swing.JRadioButton();
        cash = new javax.swing.JRadioButton();
        Booking = new javax.swing.JButton();
        HapusData = new javax.swing.JButton();
        editData = new javax.swing.JButton();
        tanggal = new javax.swing.JComboBox<>();
        bulan = new javax.swing.JComboBox<>();
        tahun = new javax.swing.JComboBox<>();
        hargaPerJam = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hargaLapangan = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setText("Silahkan Isi Data dibawah Untuk Melakukan Penyewaan ");

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel12.setText("Kembali");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );

        jLabel2.setText("Nama Penyewa");

        jLabel3.setText("Jenis Lapangan");

        JnsLap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lapangan Interlock 1", "Lapangan Interlock 2", "Lapangan Sintetis 1", "Lapangan Sintetis 2" }));
        JnsLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JnsLapActionPerformed(evt);
            }
        });

        TGLSewa.setText("Tanggal Sewa");

        NamaPenyewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaPenyewaActionPerformed(evt);
            }
        });

        WktSewa.setText("Waktu Sewa");

        mulai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mulai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jam Main", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel7.setText("Sampai");

        selesai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        selesai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jam Selesai", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22" }));

        JnsHari.setText("Jenis hari");

        Hari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hari", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu" }));
        Hari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HariActionPerformed(evt);
            }
        });

        Total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Total.setForeground(new java.awt.Color(255, 51, 51));
        Total.setText("Total");

        Tott.setEditable(false);
        Tott.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TottActionPerformed(evt);
            }
        });

        metodePembayaran.setText("Metode Pembayaran");

        buttonGroup1.add(transfer);
        transfer.setText("Transfer");

        buttonGroup1.add(cash);
        cash.setText("Cash");

        Booking.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Booking.setText("Booking");
        Booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingActionPerformed(evt);
            }
        });

        HapusData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HapusData.setText("Hapus Data");
        HapusData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusDataActionPerformed(evt);
            }
        });

        editData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editData.setText("Edit Data");
        editData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDataActionPerformed(evt);
            }
        });

        tanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanggal", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalActionPerformed(evt);
            }
        });

        bulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bulan", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember", " " }));

        tahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tahun", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", " " }));

        hargaPerJam.setText("-");

        jLabel6.setText("Harga Tambahan ");

        jLabel4.setText("Harga Perlapangan");

        hargaLapangan.setText("-");

        jLabel8.setText("Harga");

        harga.setText("-");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama ", "Jenis Lapangan", "Tanggal Sewa", "Jenis Hari", "Waktu Sewa", "Harga", "Pelunasan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel10.setText("Silahkan Lihat Jadwal Di Bawah");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(TGLSewa))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JnsLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NamaPenyewa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hargaLapangan, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(JnsHari)
                                .addGap(65, 65, 65)
                                .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(bulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(hargaPerJam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(WktSewa)
                                    .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(134, 134, 134))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Tott, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Hari, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(mulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(43, 43, 43)
                        .addComponent(selesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(metodePembayaran)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cash)
                            .addComponent(transfer))))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(29, 29, 29))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(HapusData)
                .addGap(133, 133, 133)
                .addComponent(Booking, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editData)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NamaPenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JnsLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargaPerJam)
                    .addComponent(hargaLapangan)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TGLSewa)
                        .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(harga)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JnsHari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(selesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WktSewa))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Total)
                    .addComponent(Tott, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(metodePembayaran)
                    .addComponent(transfer))
                .addGap(18, 18, 18)
                .addComponent(cash)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HapusData)
                    .addComponent(Booking)
                    .addComponent(editData))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NamaPenyewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaPenyewaActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_NamaPenyewaActionPerformed

    private void JnsLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JnsLapActionPerformed
        // TODO add your handling code here:
        
        if (JnsLap.getSelectedItem().equals("Lapangan Interlock 1")){
            hargaLapangan.setText("100000");
        }
        if (JnsLap.getSelectedItem().equals("Lapangan Interlock 2")){
            hargaLapangan.setText("100000");
        }
        if (JnsLap.getSelectedItem().equals("Lapangan Sintetis 1")){
            hargaLapangan.setText("120000");
        }
        if (JnsLap.getSelectedItem().equals("Lapangan Sintetis 1")){
            hargaLapangan.setText("120000");
        }
    }//GEN-LAST:event_JnsLapActionPerformed

    private void TottActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TottActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TottActionPerformed

    private void BookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingActionPerformed
          
    if (NamaPenyewa.getText().isEmpty()) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        
        JOptionPane.showMessageDialog(this, "Nama Penyewa tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }
         

        String nama = NamaPenyewa.getText();
        String jenisLapangan = (String) JnsLap.getSelectedItem();
        String tanggal = (String) this.tanggal.getSelectedItem();
        String bulan = (String) this.bulan.getSelectedItem();
        String tahun = (String) this.tahun.getSelectedItem();
        String tanggalSewa = tanggal + " " + bulan + " " + tahun;
        String hari = (String) Hari.getSelectedItem();
        String jamMulai = (String) mulai.getSelectedItem();
        String jamSelesai = (String) selesai.getSelectedItem();
        String waktuSewa = jamMulai + " - " + jamSelesai;

        
        System.out.println("Nama Penyewa: " + nama);
        System.out.println("Jenis Lapangan: " + jenisLapangan);
        System.out.println("Tanggal Sewa: " + tanggalSewa);
        System.out.println("Jenis Hari: " + hari);
        System.out.println("Waktu Sewa: .00"+waktuSewa+".00");
        System.out.println("Metode Pembayaran: " + metodePembayaran);
        
        int getHarga = Integer.parseInt(hargaLapangan.getText());
        int getHari = Integer.parseInt(hargaPerJam.getText());
        int Harga = getHarga + getHari;
        String putHarga = Integer.toString(Harga);
        
        harga.setText(putHarga);
   
        int jamMulaiInt = Integer.parseInt(jamMulai);  
        int jamSelesaiInt = Integer.parseInt(jamSelesai);     
        int durasiSewa = jamSelesaiInt - jamMulaiInt;
        
        String metodePembayaran = "";
        if (cash.isSelected()) {
        metodePembayaran = "Cash";
        } else if (transfer.isSelected()) {
        metodePembayaran = "Transfer";
        } else {
        JOptionPane.showMessageDialog(this, "Silakan pilih metode pembayaran!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }

        // Perhitungan total harga
        int totalHarga = Harga * durasiSewa;
        Tott.setText("" + totalHarga);

        model.addRow(new Object[]{nama, jenisLapangan, tanggalSewa, hari, waktuSewa, totalHarga, metodePembayaran});        
        DataSewaBoss data = new DataSewaBoss(nama, jenisLapangan, tanggalSewa, hari, waktuSewa, Harga, metodePembayaran);
                     
        if (Daftar1 != null) {
        Daftar1.updateTable(nama, jenisLapangan, tanggalSewa, hari, waktuSewa, Harga, metodePembayaran);
        } else {
        System.out.println("Daftar1 belum diinisialisasi.");
        }

        dataList.add(data);
   

    }//GEN-LAST:event_BookingActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        a daftar = (a) SwingUtilities.getWindowAncestor(this);
        if (daftar != null) {
            daftar.showPanel("home");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void HapusDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusDataActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Silakan pilih data yang ingin dihapus.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.removeRow(selectedRow);
        
        if (selectedRow < dataList.size()) {
        dataList.remove(selectedRow);
        }
//        saveDataToFile();
    }//GEN-LAST:event_HapusDataActionPerformed

    private void editDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDataActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Silakan pilih data yang ingin diedit.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String nama = (String) model.getValueAt(selectedRow, 0);
        String jenisLapangan = (String) model.getValueAt(selectedRow, 1);
        String tanggalSewa = (String) model.getValueAt(selectedRow, 2);
        String hari = (String) model.getValueAt(selectedRow, 3);
        String waktuSewa = (String) model.getValueAt(selectedRow, 4);
        int totalHarga = (int) model.getValueAt(selectedRow, 5);

        NamaPenyewa.setText(nama);
        JnsLap.setSelectedItem(jenisLapangan);
        String[] tanggalArray = tanggalSewa.split(" ");
        tanggal.setSelectedItem(tanggalArray[0]);
        bulan.setSelectedItem(tanggalArray[1]);
        tahun.setSelectedItem(tanggalArray[2]);
        Hari.setSelectedItem(hari);
        String[] waktuArray = waktuSewa.split(" - ");
        mulai.setSelectedItem(waktuArray[0]);
        selesai.setSelectedItem(waktuArray[1]);

       
        model.removeRow(selectedRow);
    }//GEN-LAST:event_editDataActionPerformed

    private void tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalActionPerformed

    private void HariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HariActionPerformed
        // TODO add your handling code here:
        
         if (Hari.getSelectedItem().equals("Hari")){
            hargaPerJam.setText("");
        }
         else if (Hari.getSelectedItem().equals("Senin")){
            hargaPerJam.setText("0");
        }
         else if (Hari.getSelectedItem().equals("Selasa")){
            hargaPerJam.setText("0");
        }
         else if (Hari.getSelectedItem().equals("Rabu")){
            hargaPerJam.setText("0");
        }
         else if (Hari.getSelectedItem().equals("Kamis")){
            hargaPerJam.setText("0");
        }
         else if (Hari.getSelectedItem().equals("Jumat")){
            hargaPerJam.setText("0");
        }
         else if (Hari.getSelectedItem().equals("Sabtu")){
            hargaPerJam.setText("30000");
        }
         else if (Hari.getSelectedItem().equals("Minggu")){
            hargaPerJam.setText("30000");
        }
    }//GEN-LAST:event_HariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Booking;
    private javax.swing.JButton HapusData;
    private javax.swing.JComboBox<String> Hari;
    private javax.swing.JLabel JnsHari;
    private javax.swing.JComboBox<String> JnsLap;
    private javax.swing.JTextField NamaPenyewa;
    private javax.swing.JLabel TGLSewa;
    private javax.swing.JLabel Total;
    private javax.swing.JTextField Tott;
    private javax.swing.JLabel WktSewa;
    private javax.swing.JComboBox<String> bulan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cash;
    private javax.swing.JButton editData;
    private javax.swing.JLabel harga;
    private javax.swing.JLabel hargaLapangan;
    private javax.swing.JLabel hargaPerJam;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel metodePembayaran;
    private javax.swing.JComboBox<String> mulai;
    private javax.swing.JComboBox<String> selesai;
    private javax.swing.JComboBox<String> tahun;
    private javax.swing.JComboBox<String> tanggal;
    private javax.swing.JRadioButton transfer;
    // End of variables declaration//GEN-END:variables
}
